# This file details the dependencies between all services, to determine which tests/builds must run for a given push to a branch, or a pull request
# Meant for consumption by the GHA: https://github.com/dorny/paths-filter
# The keys in this file are keys for other workflow jobs to be run when changes on the specified paths are detected

kork: &kork
- 'kork/**'

fiat: &fiat
- 'fiat/**'
- *kork

buildtool:
- 'buildtool/**'

clouddriver: &clouddriver
- 'clouddriver/**'
- *fiat
- *kork

deck-kayenta: &deck-kayenta
- 'deck-kayenta/**'

deck:
- 'deck/**'
- *deck-kayenta

echo: &echo
- 'echo/**'
- *fiat
- *kork

front50: &front50
- 'front50/**'
- *fiat
- *kork

gate: &gate
- 'gate/**'
- *fiat
- *kork

halyard: &halyard
- 'halyard/**'

igor: &igor
- 'igor/**'
- *fiat
- *kork

orca: &orca
- 'orca/**'
- *fiat
- *kork

kayenta: &kayenta
- 'kayenta/**'
- *fiat
- *kork
- *orca

rosco: &rosco
- 'rosco/**'
- *kork

spin: &spin
- 'spin/**'

spinnaker-gradle-project:
- 'spinnaker-gradle-project/**'
