name: Buildtool

on:
  push:
    branches:
      - 'main'
      - 'release-*'
    paths:
      - 'buildtool/**'

  pull_request:
    branches:
      - 'main'
      - 'release-*'
    paths:
      - 'buildtool/**'

jobs:
  build:
    # Only run this on repositories in the 'spinnaker' org, not on forks.
    if: startsWith(github.repository, 'jcavanagh/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies with pip
        run: |
          pip install -r buildtool/dev/requirements.txt
          pip install -r buildtool/dev/buildtool/requirements.txt
      - name: Install regctl for container image tagging
        run: |
          curl -L https://github.com/regclient/regclient/releases/download/v0.4.5/regctl-linux-amd64 >regctl
          install --mode 755 regctl /usr/local/bin/
          regctl version
      - name: Setup for tests
        run: |
          git config --global user.email "sig-platform@spinnaker.io"
          git config --global user.name "Spinnaker GHA"
      - run: buildtool/unittest/run_tests.sh

  pr-extras:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build
    steps:
      - name: Install dependencies with pip
        run: |
          pip install flake8
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-the-python-starter-workflow
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
