name: Deck-Kayenta Build

on:
  pull_request:
    paths:
      - 'deck-kayenta/**'
  push:
    branches:
      - main
      - release-*
    paths:
      - 'deck-kayenta/**'

env:
  NODE_VERSION: 12.16.0

defaults:
  run:
    working-directory: ./deck-kayenta

jobs:
  ci:
    # Meta-job that depends on the other job statuses.  Branch protection then checks this job status.
    name: Deck-Kayenta CI
    if: startsWith(github.repository, 'jcavanagh/')
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - run: echo test, build successful

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION  }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Unit Tests
        run: yarn test

  build:
    name: Production Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION  }}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Yarn Build
        run: yarn build
