name: Publish to NPM

on:
  push:
    branches:
      - 'main'
    paths:
      - 'deck-kayenta/package.json'

env:
  NODE_VERSION: 12.16.0

defaults:
  run:
    working-directory: ./deck-kayenta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION  }}
      - name: publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          build_scripts/publish_github_actions.sh
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
