name: Fiat
run-name: Fiat ${{ github.ref_name }} (${{ github.event_name }})

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - release-*
    paths:
      - 'fiat/**'
      - 'kork/**'

  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'fiat/**'
      - 'kork/**'

jobs:
  fiat:
    uses: ./.github/workflows/generic-build-publish.yml
    with:
      project: fiat
      publish: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
