name: Igor
run-name: Igor ${{ github.ref_name }} (${{ github.event_name }})

on:
  workflow_dispatch:
    inputs:
      skip-tests:
        description: If specified, does not run tests
        type: boolean
        default: false

  push:
    branches:
      - main
      - release-*
    paths:
      - 'igor/**'
      - 'fiat/**'
      - 'kork/**'

  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'igor/**'
      - 'fiat/**'
      - 'kork/**'

jobs:
  igor:
    uses: ./.github/workflows/generic-build-publish.yml
    with:
      project: igor
      publish: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
