name: Igor
run-name: Igor ${{ github.ref_name }} (${{ github.event_name }})

on:
  workflow_call:
  workflow_dispatch:

  push:
    branches:
      - main
      - release-*
    paths:
      - 'igor/**'
      - 'fiat/**'
      - 'kork/**'

  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'igor/**'
      - 'fiat/**'
      - 'kork/**'

jobs:
  igor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/generic-build-publish
        with:
          project: igor
          gradle-cmd-opts: -PenableCrossCompilerPlugin=true
          publish: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gar-json-key: ${{ secrets.GAR_JSON_KEY }}
