name: Keel
run-name: Keel ${{ github.ref_name }} (${{ github.event_name }})

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - release-*
    paths:
      - 'keel/**'
      - 'fiat/**'
      - 'kork/**'

  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'keel/**'
      - 'fiat/**'
      - 'kork/**'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx8g -Xms8g

jobs:
  keel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/generic-build-publish
        with:
          project: keel
          publish: ${{ github.event_name != 'pull_request' }}
          publish-halconfig: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gar-json-key: ${{ secrets.GAR_JSON_KEY }}
