name: Rebuild All/New Branch First Build
run-name: ${{ github.event_name == 'workflow_dispatch' && format('Manual Rebuild All ({0})', github.ref_name) || format('New Branch Creation ({0})', github.ref_name) }}

# There is an issue with push triggers where it does not trigger on new branches if there are path filters
# This makes new release branches difficult, as we need an initial build
# So, we use this to check `create` events, and see if we should run everything
# https://github.com/orgs/community/discussions/26286#discussioncomment-3251208
on:
  create:
  workflow_dispatch:

jobs:
  # There's also no way to apply a condition to all jobs in a workflow, so we end up with this beautiful disaster
  clouddriver:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/clouddriver.yml
    secrets: inherit
  deck:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/deck.yml
    secrets: inherit
  deck-kayenta:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/deck-kayenta.yml
    secrets: inherit
  echo:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/echo.yml
    secrets: inherit
  fiat:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/fiat.yml
    secrets: inherit
  front50:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/front50.yml
    secrets: inherit
  gate:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/gate.yml
    secrets: inherit
  halyard:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/halyard.yml
    secrets: inherit
  igor:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/igor.yml
    secrets: inherit
  kayenta:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/kayenta.yml
    secrets: inherit
  keel:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/keel.yml
    secrets: inherit
  orca:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/orca.yml
    secrets: inherit
  rosco:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/rosco.yml
    secrets: inherit
  spin:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/spin.yml
    secrets: inherit
  libs:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'create' && startsWith(github.ref, 'refs/heads/release-'))
    uses: ./.github/workflows/spinnaker-libraries.yml
    secrets: inherit
