name: Rosco
run-name: Rosco ${{ github.ref_name }} (${{ github.event_name }})

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - release-*
    paths:
      - 'rosco/**'
      - 'fiat/**'
      - 'kork/**'

  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'rosco/**'
      - 'fiat/**'
      - 'kork/**'

jobs:
  rosco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/generic-build-publish
        with:
          project: rosco
          publish: ${{ github.event_name != 'pull_request' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gar-json-key: ${{ secrets.GAR_JSON_KEY }}
