name: Spinnaker Libraries
run-name: Libraries ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'clouddriver/**'
      - 'echo/**'
      - 'fiat/**'
      - 'front50/**'
      - 'gate/**'
      - 'halyard/**'
      - 'igor/**'
      - 'kayenta/**'
      - 'keel/**'
      - 'kork/**'
      - 'orca/**'
      - 'rosco/**'

  #    secrets:
#      NEXUS_USERNAME:
#        description: Nexus publishing username
#        required: false
#      NEXUS_PASSWORD:
#        description: Nexus publishing password
#        required: false
#      NEXUS_PGP_SIGNING_KEY:
#        description: Nexus PGP signing key
#        required: false
#      NEXUS_PGP_SIGNING_PASSWORD:
#        description: Nexus PGP signing password
#        required: false

jobs:
  #  publish-libraries-nexus:
#    runs-on: ubuntu-latest
#    if: inputs.publish == 'true'
#    needs:
#      - version
#      - build
#    steps:
#      - name: Publish Maven libraries
#        env:
#          ORG_GRADLE_PROJECT_version: ${{ needs.version.outputs.version }}
#          ORG_GRADLE_PROJECT_nexusPublishEnabled: true
#          ORG_GRADLE_PROJECT_nexusStagingUrl: ${{ }}
#          ORG_GRADLE_PROJECT_nexusSnapshotUrl: ${{ }}
#          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
#          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}
#          ORG_GRADLE_PROJECT_nexusPgpSigningKey: ${{ secrets.NEXUS_PGP_SIGNING_KEY }}
#          ORG_GRADLE_PROJECT_nexusPgpSigningPassword: ${{ secrets.NEXUS_PGP_SIGNING_PASSWORD }}
#        run: |
#          ./gradlew build ${{ inputs.project }}-web:installDist publishToNexus closeAndReleaseNexusStagingRepository

  version:
    uses: ./.github/workflows/version.yml
    with:
      project: spinnaker

  libraries:
    runs-on: ubuntu-latest
    needs:
      - version
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: zulu
          cache: ${{ !env.ACT && 'gradle' || '' }} # Disable Gradle cache when running actions locally

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v1
        # use service account flow defined at: https://github.com/google-github-actions/upload-cloud-storage#authenticating-via-service-account-key-json
        with:
          credentials_json: ${{ secrets.GAR_JSON_KEY }}

      - name: Publish libs to Google Artifact Registry
        env:
          ORG_GRADLE_PROJECT_version: ${{ needs.version.outputs.version }}
          ORG_GRADLE_PROJECT_artifactRegistryPublishEnabled: true
          ORG_GRADLE_PROJECT_artifactRegistryPublishAptEnabled: false
          ORG_GRADLE_PROJECT_artifactRegistryPublishMavenEnabled: true
          ORG_GRADLE_PROJECT_artifactRegistryMavenProject: spinnaker-monorepo-test
          ORG_GRADLE_PROJECT_artifactRegistryMavenLocation: us-west2
          GAR_JSON_KEY: ${{ secrets.GAR_JSON_KEY }}
        run: |
          ./gradlew :publishJava
