name: Spinnaker Release

on:
  workflow_dispatch:
    inputs:
      spinnaker-version:
        description: Spinnaker release version, e.g. 2023.1.1
        type: string
        required: true
      previous-version:
        description: Previous Spinnaker release version to use for changelogs.  If not specified, infers previous from the `spinnaker-version` input.
        type: string
        required: false
      dry-run:
        type: boolean
        description: Dry run by default
        default: true

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g

jobs:
  spinnaker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Spinnaker release BoM and changelog
        uses: ./.github/actions/spinnaker-release
        with:
          version: ${{ inputs.spinnaker-version }}
          previous_version: ${{ inputs.previous-version }}
          branch: ${{ github.ref }}
          dry_run: ${{ inputs.dry-run }}

  gh-release:
    runs-on: ubuntu-latest
    needs:
      - spinnaker-release
    if: inputs.dry-run != 'false'
    steps:
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: spinnaker-release-${{ inputs.spinnaker-version }}
          release_name: Spinnaker ${{ inputs.spinnaker-version }}
          body: |
            ${{ needs.spinnaker-release.outputs.changelog }}
          draft: false
          prerelease: false
