name: Spinnaker Release
run-name: Spinnaker Release (${{ inputs.spinnaker-version }} dry=${{ inputs.dry-run }})

on:
  workflow_dispatch:
    inputs:
      spinnaker-version:
        description: Spinnaker release version, e.g. 2023.1.1 or 1.36.1 or main.1
        type: string
      previous-version:
        description: (optional) Previous Spinnaker release version to use for changelogs.  If not specified, infers previous from the `spinnaker-version` input.
        type: string
      add-to-versions-yml:
        description: Add this version to `versions.yml` for Halyard?
        type: boolean
        default: true
      branch:
        description: (optional) Manually specify reference branch for image selection and versioning, if the inference from the above version does not work.
      dry-run:
        type: boolean
        description: Dry run?
        default: true

jobs:
  spinnaker-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - id: version
        uses: ./.github/actions/version
        if: inputs.spinnaker-version == ''
        with:
          project: spinnaker
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-increment: ${{ inputs.dry-run != 'false' }}

      - name: Process Inputs
        shell: bash
        run: |
          if [[ '${{ inputs.spinnaker-version }}' == '' ]]; then
            echo "spinnaker-version=${{ steps.version.release-train }}.${{ steps.version.build-number }}" >> "$GITHUB_ENV"
          else
            echo "spinnaker-version=${{ inputs.spinnaker-version }}" >> "$GITHUB_ENV"
          fi

      - name: Create Spinnaker release BoM and changelog
        id: spinnaker-release
        uses: ./.github/actions/spinnaker-release
        with:
          credentials-json: ${{ secrets.GAR_JSON_KEY }}
          branch: ${{ inputs.branch }}
          version: ${{ env.spinnaker-version }}
          previous-version: ${{ inputs.previous-version }}
          dry-run: ${{ inputs.dry-run }}

      - name: Create Github release
        if: inputs.dry-run == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: spinnaker-release-${{ inputs.spinnaker-version }}
          release_name: Spinnaker ${{ inputs.spinnaker-version }}
          body: |
            ${{ steps.spinnaker-release.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Summarize
        shell: bash
        if: github.event_name != 'pull_request'
        run: |
          echo "### Release Info" >> "$GITHUB_STEP_SUMMARY"
          echo "| | |" >> "$GITHUB_STEP_SUMMARY"
          echo "| --- | --- |" >> "$GITHUB_STEP_SUMMARY"
          echo "| __Version__ | ${{ inputs.spinnaker-version }} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| __BoM__ | ${{ steps.spinnaker-release.outputs.bom-url }} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| __Changelog__ | ${{ steps.spinnaker-release.outputs.bom-url }} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| __versions.yml__ | ${{ steps.spinnaker-release.outputs.versions-yml-url }} |" >> "$GITHUB_STEP_SUMMARY"
          echo "<details>" >> "$GITHUB_STEP_SUMMARY"
          echo "<summary>BoM Contents</summary>" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.spinnaker-release-outputs.bom }}" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "</details>" >> "$GITHUB_STEP_SUMMARY"
          echo "<details>" >> "$GITHUB_STEP_SUMMARY"
          echo "<summary>Changelog Contents</summary>" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.spinnaker-release-outputs.changelog }}" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "</details>" >> "$GITHUB_STEP_SUMMARY"
          echo "<details>" >> "$GITHUB_STEP_SUMMARY"
          echo "<summary>versions.yml Contents</summary>" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.spinnaker-release-outputs.versions-yml }}" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
          echo "</details>" >> "$GITHUB_STEP_SUMMARY"
