name: Spinnaker Gradle Project

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'spinnaker-gradle-project/**'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - id: version
        uses: ./.github/actions/version
        with:
          namespace: 'spinnaker-gradle-project'
          version-override: ${{ github.event_name == 'workflow_call' && inputs.version-override || '' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release build (Gradle plugin portal)
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          ORG_GRADLE_PROJECT_version: ${{ steps.version.outputs.version }}
        run: |
          ./gradlew --info -Pgradle.publish.key="${GRADLE_PUBLISH_KEY}" -Pgradle.publish.secret="${GRADLE_PUBLISH_SECRET}" :spinnaker-gradle-project:publishPlugins
