name: Spinnaker Libraries
run-name: Libraries ${{ github.ref_name }}

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'clouddriver/**'
      - 'echo/**'
      - 'fiat/**'
      - 'front50/**'
      - 'gate/**'
      - 'halyard/**'
      - 'igor/**'
      - 'kayenta/**'
      - 'keel/**'
      - 'kork/**'
      - 'orca/**'
      - 'rosco/**'

jobs:
  libraries-gar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/version
        id: version
        with:
          project: spinnaker-libraries
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          java-version: |
            11
            17
          distribution: zulu
          cache: ${{ !env.ACT && 'gradle' || '' }} # Disable Gradle cache when running actions locally

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v2
        # use service account flow defined at: https://github.com/google-github-actions/upload-cloud-storage#authenticating-via-service-account-key-json
        with:
          credentials_json: ${{ secrets.GAR_JSON_KEY }}

      - name: Publish libs to Google Artifact Registry
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.version.outputs.version }}
          ORG_GRADLE_PROJECT_artifactRegistryPublishEnabled: true
          ORG_GRADLE_PROJECT_artifactRegistryPublishAptEnabled: false
          ORG_GRADLE_PROJECT_artifactRegistryPublishMavenEnabled: true
          ORG_GRADLE_PROJECT_artifactRegistryMavenProject: spinnaker-monorepo-test
          ORG_GRADLE_PROJECT_artifactRegistryMavenLocation: us-west2
          GAR_JSON_KEY: ${{ secrets.GAR_JSON_KEY }}
        run: |
          ./gradlew assemble publish

#  libraries-nexus:
#    runs-on: ubuntu-latest
#    needs:
#      - version
#    steps:
#      - name: Publish Nexus libraries
#        env:
#          ORG_GRADLE_PROJECT_version: ${{ steps.version.outputs.version }}
#          ORG_GRADLE_PROJECT_nexusPublishEnabled: true
#          ORG_GRADLE_PROJECT_nexusStagingUrl: ${{  }}
#          ORG_GRADLE_PROJECT_nexusSnapshotUrl: ${{  }}
#          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
#          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}
#          ORG_GRADLE_PROJECT_nexusPgpSigningKey: ${{ secrets.NEXUS_PGP_SIGNING_KEY }}
#          ORG_GRADLE_PROJECT_nexusPgpSigningPassword: ${{ secrets.NEXUS_PGP_SIGNING_PASSWORD }}
#        run: |
#          ./gradlew assemble ${{ inputs.project }}-web:installDist publishToNexus closeAndReleaseNexusStagingRepository
